### PR TITLE
feat: support multiple pool node key on same HW wallet

### PR DESCRIPTION
**Pull request by ArchiFleKs**
Signed-off-by: Kevin Lefevre <kevin@particule.io>

### CODE REVIEW

**Comment by gitmachtl** [comment]
hi, thx for the commit. let me check it, because this an "out of the specs" feature. let me talk with my buddies from vacuumlabs if this is ok. i am currently away and will check this out on the weekend. best regards, martin

**Comment by ArchiFleKs** [comment]
@gitmachtl Yes I know the specs is supposed to be [hardcoded](https://developers.cardano.org/docs/governance/cardano-improvement-proposals/cip-1853/). Do you think this could lead to issues ? I launched 3 pools using the same ledger.

**Comment by gitmachtl** [comment]
yep, the CIP is using the hardened index 0 for that. i contacted samuel leathers to get a feedback on that topic too. i do stuff that "hey it just works" all the time :-) but would be good to have an ok on that from them.

**Comment by gitmachtl** [comment]
ColdKeyIndex option is now added into the scripts
https://github.com/gitmachtl/scripts/commit/2d5bf77bbf0a54602eba88844d9a8d97bf6d242a

Its working for the whole range 0-2147483647

Best regards, Martin

**Comment by ArchiFleKs** [comment]
> ColdKeyIndex option is now added into the scripts
> https://github.com/gitmachtl/scripts/commit/2d5bf77bbf0a54602eba88844d9a8d97bf6d242a
> 
> Its working for the whole range 0-2147483647
> 
> Best regards, Martin

Nice thank you

**Pull request closed without merging**
